services:
  localstack:
    image: localstack/localstack:0.14.3
    ports:
      - "4566:4566"   # edge
      - "4572:4572"   # legacy S3 (必要なら)
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/var/localstack/data
    volumes:
      - localstack-data:/var/localstack/data

volumes:
  localstack-data: